name: "composer.json normalizer"

on:
  pull_request:
    paths:
      - 'composer.json'

  push:
    paths:
      - 'composer.json'

jobs:
  composer-normalize:
    name: composer-normalize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action:latest

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: composer.json
          commit_message: "Normalize composer.json (CI)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
