name: "composer.json normalizer"

on:
  pull_request:
    paths:
      - 'composer.json'

  push:
    paths:
      - 'composer.json'

jobs:
  composer-normalize:
    name: composer-normalize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action:latest
